### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by 23650** [17TheWord/qinglan_bot#8]
完全按照文档操作来执行，但最终<ql run>步骤时无法启动
**操作步骤：**
![image](https://github.com/17TheWord/qinglan_bot/assets/82879659/f67fe595-54e6-4488-a7ee-05936e3115fa)

### 报错信息：（挺短的就不折叠了）
D:\XiaoDuo-Bot\QingLanBot>ql run
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\ql.exe\__main__.py", line 4, in <module>
    from qinglan_bot.cli_start import main
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\qinglan_bot\__init__.py", line 1, in <module>
    from nonebot import get_driver, ReverseDriver
ImportError: cannot import name 'ReverseDriver' from 'nonebot' (C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py)

### nonebot2版本：2.1.0（自动安装）

**Comment by 17TheWord** [comment]
最近没有时间维护，可以的话请更换mcqq插件

**Comment by 17TheWord** [comment]
已在 [v0.1.6](https://github.com/17TheWord/qinglan_bot/releases/tag/v0.1.6) 修复
